/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.s3project.block.Tools;

import com.badlogic.gdx.files.FileHandle;
import com.badlogic.gdx.utils.Array;
import com.badlogic.gdx.utils.Json;
import com.badlogic.gdx.utils.JsonWriter;
import com.s3project.block.Objects.Skill;
import java.io.UnsupportedEncodingException;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author S34n4e
 */
public class SkillWdw extends javax.swing.JDialog {

    /**
     * Creates new form SkillWdw
     */
    private Array<Skill> list;
    private int id;
    private int idMax;

    public SkillWdw(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        Skill skill = new Skill();
        id = 0;
        list = new Array<Skill>();

        try {
            FileHandle file = new FileHandle("skills.txt");//load file --done
            Json json = new Json(JsonWriter.OutputType.json);
            json.addClassTag("skills", list.getClass());
            list = new Json().fromJson(list.getClass(), file);
            list.sort();

        } catch (Exception e) {
            FileHandle file = new FileHandle("ouchSave.txt");
            file.writeString("- This is a test -", true);
        }

        //list.add(new Skill(1, "test", "descr", 55, Skill.Type.BUFF, Skill.Target.FOE,
        //Skill.Stat.ATK, Skill.Element.NO, Skill.Buff.NO, Skill.Buff.NO, Skill.Debuff.BLIND, Skill.Debuff.NO, Skill.Cooldown.VFAST, 1, 1));
        idMax = list.size-1;
        jLabelMaxSize.setText(idMax + "");
        
        Vector columnData1 = new Vector();
        Vector columnData2 = new Vector();
        Iterator<Skill> it = list.iterator();
        while(it.hasNext()){
            Skill temp = it.next();
        columnData1.add(temp.getId());
        columnData2.add(temp.getName());
        }
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("id", columnData1);
        table.addColumn("Name", columnData2);
        jTable.setModel(table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jbuff2 = new javax.swing.JComboBox<String>();
        jLabel10 = new javax.swing.JLabel();
        jdebuff1 = new javax.swing.JComboBox<String>();
        jdebuff2 = new javax.swing.JComboBox<String>();
        jLabel11 = new javax.swing.JLabel();
        jcooldown = new javax.swing.JComboBox<String>();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButtonSave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonAddNew = new javax.swing.JButton();
        jpower = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jsound = new javax.swing.JSpinner();
        jtype = new javax.swing.JComboBox<String>();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        janim = new javax.swing.JSpinner();
        jtarget = new javax.swing.JComboBox<String>();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelMaxSize = new javax.swing.JLabel();
        jstat = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        jelement = new javax.swing.JComboBox<String>();
        jButtonExit = new javax.swing.JButton();
        jid = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jdesc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jbuff1 = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbuff2.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "NO", "ATK30", "MAG30", "ESP30", "AGI30", "BARFIRE", "BARWATER", "BARLIT", "REGEN", "ASTRA" }));

        jLabel10.setText("Debuff");

        jdebuff1.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "NO", "ATK", "MAG", "ESP", "AGI", "POISON", "BLIND", "SLEEP", "DISABLE" }));

        jdebuff2.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "NO", "ATK", "MAG", "ESP", "AGI", "POISON", "BLIND", "SLEEP", "DISABLE" }));

        jLabel11.setText("Cooldown");

        jcooldown.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "VSLOW", "SLOW", "FAST", "VFAST" }));

        jButtonSave.setText("Guardar todo");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabel4.setText("Power");

        jButtonAddNew.setText("Agregar habilidad nueva");
        jButtonAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNewActionPerformed(evt);
            }
        });

        jLabel12.setText("Sound");

        jLabel5.setText("Type");

        jtype.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "NO", "DMG", "DMGDEBUFF", "DMGBUFF", "HEAL", "HEALBUFF", "DMGHEAL", "DRAIN", "BUFF", "DEBUFF" }));

        jLabel13.setText("Anim");

        jLabel6.setText("Target");

        jtarget.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "NO", "USER", "FOE", "FOES", "ALLY", "ALLIES", "ALL" }));

        jLabel14.setText("MAX:");

        jLabel7.setText("Stat");

        jLabelMaxSize.setText("15");

        jstat.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "NO", "VIT", "ATK", "MAG", "ESP", "AGI" }));

        jLabel8.setText("Element");

        jelement.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "NO", "FIRE", "WATER", "LIGHTNING" }));

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jid.setToolTipText("");
        jid.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jidStateChanged(evt);
            }
        });
        jid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jidFocusLost(evt);
            }
        });
        jid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jidKeyReleased(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Name");

        jname.setText("name");

        jLabel3.setText("Description");

        jdesc.setText("description");

        jLabel9.setText("Buff");

        jbuff1.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "NO", "ATK30", "MAG30", "ESP30", "AGI30", "BARFIRE", "BARWATER", "BARLIT", "REGEN", "ASTRA" }));

        jButton1.setText("Confirmar cambios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jname, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdesc))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcooldown, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jsound, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(janim, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonExit))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMaxSize)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAddNew))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbuff1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbuff2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jdebuff1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jdebuff2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jpower, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtype, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtarget, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jstat, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jelement, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddNew)
                    .addComponent(jLabel14)
                    .addComponent(jLabelMaxSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jstat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jelement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jbuff1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuff2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jdebuff1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdebuff2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jcooldown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExit)
                    .addComponent(jButtonSave)
                    .addComponent(jLabel12)
                    .addComponent(jsound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(janim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editor", jPanel1);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.setEnabled(false);
        jScrollPane1.setViewportView(jTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tabla", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNewActionPerformed

        list.add(new Skill(idMax, "nameHere", "descrHere", 55, Skill.Type.BUFF, Skill.Target.FOE,
                Skill.Stat.ATK, Skill.Element.NO, Skill.Buff.NO, Skill.Buff.NO, Skill.Debuff.BLIND, Skill.Debuff.NO, Skill.Cooldown.VFAST, 1, 1));
        Skill temp = list.get(list.size - 1);
        jid.setValue(temp.getId());
        jname.setText(temp.getName());
        jdesc.setText(temp.getDescription());
        jpower.setValue(temp.getPower());
        jtype.getModel().setSelectedItem(temp.getType());
        jtarget.getModel().setSelectedItem(temp.getTarget());
        jstat.getModel().setSelectedItem(temp.getStat());
        jelement.getModel().setSelectedItem(temp.getElement());
        jbuff1.getModel().setSelectedItem(temp.getBuff1());
        jbuff2.getModel().setSelectedItem(temp.getBuff2());
        jdebuff1.getModel().setSelectedItem(temp.getDeb1());
        jdebuff2.getModel().setSelectedItem(temp.getDeb2());
        jcooldown.getModel().setSelectedItem(temp.getCdw());
        jsound.setValue(temp.getSound());
        janim.setValue(temp.getAnimation());

        idMax++;
        jLabelMaxSize.setText(idMax + " ");        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddNewActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        
        Array<Skill> templist = new Array<Skill>();
        for(int i = 0; i < list.size; i++){
            templist.add(list.get(i));
            templist.get(i).setName("" + templist.get(i).getName() + "");
        }
        
        FileHandle file = new FileHandle("skills.txt");//load file --done
        Json json = new Json(JsonWriter.OutputType.json);
        json.addClassTag("skills", templist.getClass());
        json.fromJson(list.getClass(), file);
        System.out.println( json.toJson(templist));
        try {
            //write
            file.writeBytes(json.toJson(templist).getBytes("UTF-8"), false);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(SkillWdw.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jidFocusLost
        updateEdit();        // TODO add your handling code here:
    }//GEN-LAST:event_jidFocusLost

    private void jidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jidKeyReleased
        updateEdit();        // TODO add your handling code here:
    }//GEN-LAST:event_jidKeyReleased

    private void jidStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jidStateChanged
        updateEdit();        // TODO add your handling code here:
    }//GEN-LAST:event_jidStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Skill skill = new Skill();
        skill.setId((int) jid.getValue());
        skill.setName(jname.getText());
        skill.setDescription(jdesc.getText());
        skill.setPower((int) jpower.getValue());
        skill.setType(Skill.Type.valueOf("" + jtype.getModel().getSelectedItem()));
        skill.setTarget(Skill.Target.valueOf("" + jtarget.getModel().getSelectedItem()));
        skill.setStat(Skill.Stat.valueOf("" + jstat.getModel().getSelectedItem()));
        skill.setElement(Skill.Element.valueOf("" + jelement.getModel().getSelectedItem()));
        skill.setBuff1(Skill.Buff.valueOf("" + jbuff1.getModel().getSelectedItem()));
        skill.setBuff2(Skill.Buff.valueOf("" + jbuff2.getModel().getSelectedItem()));
        skill.setDeb1(Skill.Debuff.valueOf("" + jdebuff1.getModel().getSelectedItem()));
        skill.setDeb2(Skill.Debuff.valueOf("" + jdebuff2.getModel().getSelectedItem()));
        skill.setCdw((Skill.Cooldown.valueOf("" + jcooldown.getModel().getSelectedItem())));
        skill.setSound((int) jsound.getValue());
        skill.setAnimation((int) janim.getValue());

        list.set((int) jid.getValue(), skill);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SkillWdw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SkillWdw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SkillWdw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SkillWdw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SkillWdw dialog = new SkillWdw(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddNew;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMaxSize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JSpinner janim;
    private javax.swing.JComboBox<String> jbuff1;
    private javax.swing.JComboBox<String> jbuff2;
    private javax.swing.JComboBox<String> jcooldown;
    private javax.swing.JComboBox<String> jdebuff1;
    private javax.swing.JComboBox<String> jdebuff2;
    private javax.swing.JTextField jdesc;
    private javax.swing.JComboBox<String> jelement;
    private javax.swing.JSpinner jid;
    private javax.swing.JTextField jname;
    private javax.swing.JSpinner jpower;
    private javax.swing.JSpinner jsound;
    private javax.swing.JComboBox<String> jstat;
    private javax.swing.JComboBox<String> jtarget;
    private javax.swing.JComboBox<String> jtype;
    // End of variables declaration//GEN-END:variables

    private void updateEdit() {
        // list.add(new Skill(idMax, "nameHere", "descrHere", 55, Skill.Type.BUFF, Skill.Target.FOE,
        // Skill.Stat.ATK, Skill.Element.NO, Skill.Buff.NO, Skill.Buff.NO, Skill.Debuff.BLIND, Skill.Debuff.NO, Skill.Cooldown.VFAST, 1, 1));
        try {
            Skill temp = list.get((int) jid.getModel().getValue());
            //jid.setValue(temp.getId());
            jname.setText(temp.getName());
            jdesc.setText(temp.getDescription());
            jpower.setValue(temp.getPower());
            jtype.getModel().setSelectedItem(temp.getType());
            jtarget.getModel().setSelectedItem(temp.getTarget());
            jstat.getModel().setSelectedItem(temp.getStat());
            jelement.getModel().setSelectedItem(temp.getElement());
            jbuff1.getModel().setSelectedItem(temp.getBuff1());
            jbuff2.getModel().setSelectedItem(temp.getBuff2());
            jdebuff1.getModel().setSelectedItem(temp.getDeb1());
            jdebuff2.getModel().setSelectedItem(temp.getDeb2());
            jcooldown.getModel().setSelectedItem(temp.getCdw());
            jsound.setValue(temp.getSound());
            janim.setValue(temp.getAnimation());
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage() + " :3 ");
        }
    }
}
